### ISSUE TITLE
Any reason behind enforcing the List<T> in stored procedure class?

### ISSUE THREAD

**Issue by shashankavusali** [zzzprojects/EntityFrameworkExtras#13]

**Comment by JonathanMagnan** [comment]
Hello @shashankavusali ,

If we take the following code:

```csharp
List<T> result = database.SqlQuery<T>(info.Sql, info.SqlParameters).ToList();

SetOutputParameterValues(info.SqlParameters, storedProcedure);
```

The current only reason to materialize the list is to be able after to call the SetOutputParameterValues which require the SQL to be executed.

It could be possible to advoid it but would require some custom code that we are not yet ready to add to this library (we tools ownership of the library a few weeks ago).

So at this moment, we have no plan to change it but it might happen later

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
