### ISSUE TITLE
Async version of ExecuteStoredProcedure method

### ISSUE THREAD

**Issue by TKharaishvili** [zzzprojects/EntityFrameworkExtras#15]
I needed an asynchronous version of `ExecuteStoredProcedure` method and was initially intending to offer a pull request for it, but as I found out, the `EntityFrameworkExtras.EF6` project is compiled against .NET 4 where `async` methods weren't present.

I think it would be cool to support asynchrony which nowadays is the encouraged and recommended style of programming and has been for two releases of C# already.

So if you agree to update the target framework to .NET 4.5, I'd gladly send the pull request.

**Comment by rwoodslap** [comment]
I agree, I had to pull the source code and modify it for my specific project.

**Comment by JonathanMagnan** [comment]
Hello @TKharaishvili , @rwoodslap ,

My company took ownership of this library a few weeks ago to make sure it keep being supported. The v3.0.3 has been released with async method ;)

Best Regards,

Jon
