### ISSUE TITLE
.NET Core and Entity Framework core

### ISSUE THREAD

**Issue by dominicrooijackers** [zzzprojects/EntityFrameworkExtras#20]
Hello Mike

I am using .NET Core targeting the .NET 4.5.2 framework and EF Core 1.1.0 in my project.
I liked your extension so I tried to rewrite it for .NET Core / EF Core.

My rewrite seems to work for me, maybe if you want to check it and make a official repo for this ?
For some reason it is not letting me directly upload zip files here (It says we don't support that file type) so here is the file 

https://mega.nz/#!V8gnBSzD!WaqeDjJaQwhyzw6XI87vP4J1O3pg4PzTt0yH0a0JBJk

Best regards
Dominic Rooijackers

**Comment by JonathanMagnan** [comment]
Hello @dominicrooijackers ,

Probably too late to answer but oh well ;)

My company took the ownership of this package recently, you can find the NuGet package compatible with EF Core here: https://www.nuget.org/packages/EntityFrameworkExtras.EFcore/

Best Regards,

Jon
