### ISSUE TITLE
Is it possible to have both input and output params in a sproc?

### ISSUE THREAD

**Issue by alexgman** [zzzprojects/EntityFrameworkExtras#22]
Thank you for this excellent library. 

I have a stored procedure that returns an int like so:

`RETURN @QuoteID`

I would like to be able to pass the stored procedure into my controller as a _request object_:

```
   [Route("Pricing")]
    public List<SomeOtherView> Post([FromBody] MySproc request)
    {
```

Then I'd like to be able to grab the return value here:

` var quoteId = context.Database.ExecuteStoredProcedure<SomeOtherView>(request).ToList();`

The problem I'm having when doing this is:

>     "Message": "An error has occurred.",
>     "ExceptionMessage": "Procedure or function PWB_P_PriceOrder has too many arguments specified.",
>     "ExceptionType": "System.Data.SqlClient.SqlException",
>     "StackTrace": "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean 

This is occuring because I've defined `MySproc `with an _output_ parameter:

```
    [StoredProcedure("MySproc ")]

    public class MySproc 
    {
        [StoredProcedureParameter(SqlDbType.Int, Direction = ParameterDirection.Output)]
        public int QuoteID { get; set; }

       //all the other parameters (all of them are INPUT except the one above)
```

When I get rid of the QuoteID (output) parameter from the mode, I am able to execute the stored procedure, but then **I do not get the QuoteID** in the response!

What is the proper way of passing in a model of the stored procedure representing both inputs and outputs?

**Comment by JonathanMagnan** [comment]
Hello @alexgman ,

A little bit for an answer, but here is an online example: https://dotnetfiddle.net/7F65tF

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
