### ISSUE TITLE
Upgrading target framework of the package

### ISSUE THREAD

**Issue by MahmoudSamir101** [zzzprojects/EntityFrameworkExtras#25]
ef 6.3 has been released with the support to target .net core 3. can you please upgrade the package to target .net standard 2.1 and ef 6.3, so it can be easy to use it in a project that target .net core 3 only

**Comment by JonathanMagnan** [comment]
Hello @MahmoudSamir101 ,

Probably too late to answer but oh well ;)

My company took the ownership of this package recently, you can find the NuGet package compatible with EF 6.3 here: https://www.nuget.org/packages/EntityFrameworkExtras.EF6/3.0.0

Best Regards,

Jon
