### ISSUE TITLE
How to retrieve scalar integer result of stored procedure?

### ISSUE THREAD

**Issue by fhaag** [zzzprojects/EntityFrameworkExtras#26]
I very much like the object-oriented way of invoking a stored procedure with an object that represents the SP's arguments.

Now, I would like to invoke a stored procedure that returns an integer value using the SQL `RETURN` statement.

Is there any way to get that value on the C# side? The available `ExecuteStoredProcedure` overloads appear to be either `void` or return an enumeration of some entity type ... that I don't quite know how to map, given that the result is a single scalar value and would thus at best be an anonymous table with a single nameless column.

**Comment by JonathanMagnan** [comment]
Hello @fhaag ,

My company took ownership of this library a few weeks ago to make sure it keeps being supported.

It's now possible to do something like this:

```csharp
context.Database.ExecuteStoredProcedure<int>(proc_Get_EntitySimple)
```

As you asked, we might add eventually support to return a dynamic by default. But we are still exploring the library at this moment.

Let me know if that answers to this issue.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by victorperez2911** [comment]
> Hello @fhaag ,
> 
> My company took ownership of this library a few weeks ago to make sure it keeps being supported.
> 
> It's now possible to do something like this:
> 
> ```cs
> context.Database.ExecuteStoredProcedure<int>(proc_Get_EntitySimple)
> ```
> 
> As you asked, we might add eventually support to return a dynamic by default. But we are still exploring the library at this moment.
> 
> Let me know if that answers to this issue.
> 
> Best Regards,
> 
> Jon
> 
> **Performance Libraries** `context.BulkInsert(list, options => options.BatchSize = 1000); ` [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation** `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3` [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

Does this approach really work?
```cs
public static IEnumerable<T> ExecuteStoredProcedure<T>(this DatabaseFacade database, object storedProcedure) where T : class
```

T should be "class".
