### ISSUE TITLE
Database.ExecuteStoredProcedure() does not exist

### ISSUE THREAD

**Issue by IhleMa** [zzzprojects/EntityFrameworkExtras#28]
I tried using EntityFrameworkExtras to execute a StoredProcedure using User-Defined Table Types. I followed the steps on this Github page, but in the last step I am supposed to use context.Database.ExecuteStoredProcedure() which does not exist for me. :(

**Comment by JonathanMagnan** [comment]
Perharp you are missing the using directive:

```csharp
using EntityFrameworkExtras;
```

We will probably remove the need for this in a future release.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
