### ISSUE TITLE
Varchar max length

### ISSUE THREAD

**Issue by stamminator** [zzzprojects/EntityFrameworkExtras#29]
Hello,

Is there a way to specify the max length of a `varchar` or `nvarchar` for stored procedure parameters in order to avoid implicit conversion when calling the sproc?

**Comment by JonathanMagnan** [comment]
Hello @stamminator ,

You should pass `-1`, just like you usually do with normal parameter: https://stackoverflow.com/a/973269/5619143

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
