### ISSUE TITLE
The extension  ExecuteStoredProcedure<T> of EFCore is not working with transactions

### ISSUE THREAD

**Issue by weismantelf** [zzzprojects/EntityFrameworkExtras#30]
The following sample, will always throw the following exception:

ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.

           using (AlarmDBContext ctx = OpenConnection())
            {
                using (IDbContextTransaction tx = StartTransaction(ctx))
                {
                    try
                    {
                        var proc = new sp_GetEventAlarmsMonitorData()
                        {
                        };

                        List<EventAlarmMonitorData> result = ctx.Database.ExecuteStoredProcedure<EventAlarmMonitorData>(proc).ToList();

                        ctx.SaveChanges();

                        tx.Commit();

                        return result;
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex, "ERROR ON GetEventAlarmMonitorData: " + ex.Message);
                        RollbackTransaction(tx);
                        throw;
                    }
                }
            }

The reason is that the method ExecuteStoredProcedure<T> of the DatabaseExtension class is not setting the transaction property of the DbCommand used by this method.

With the following change the ExecuteStoredProcedure<T> is working:

```
using  Microsoft.EntityFrameworkCore.Storage;

using (var command = database.GetDbConnection().CreateCommand())
 {
    command.CommandText = info.Sql;
    command.CommandType = CommandType.Text;
    command.Parameters.AddRange(info.SqlParameters);
    command.Transaction = database.CurrentTransaction.GetDbTransaction();
    // database.OpenConnection();`
   ...
}

```

**Comment by JonathanMagnan** [comment]
Hello @weismantelf ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @weismantelf ,

The v3.0.2 has been released

Let me know if everything now works as expected with a transaction.

Best Regards,

Jon
