### ISSUE TITLE
SQL command timeout values are not used in the stored procedure connections

### ISSUE THREAD

**Issue by mykiep** [zzzprojects/EntityFrameworkExtras#37]
The stored procedure calls create new connections and are not using the timeout values from the database.  This was fixed in a pull request into [rhallman/EntityFrameworkExtras](https://github.com/rhallman/EntityFrameworkExtras/commit/b08436c1829a3465ca3ed904694e7766abedfb50)

``` csharp
                command.CommandText = query;
                command.CommandType = CommandType.Text;
                int? commandTimeout = database.GetCommandTimeout();
                if (commandTimeout.HasValue)
                {
                    command.CommandTimeout = commandTimeout.Value;
                }
                command.Parameters.AddRange(parameters);
                database.OpenConnection();
```

**Comment by JonathanMagnan** [comment]
Hello @mykiep ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mykiep ,

The v3.0.6 has been released.

Let me know if everything is now working as expected.

Best Regards,

Jon

**Comment by mykiep** [comment]
Thanks for resolving this so quickly!
