### ISSUE TITLE
How to map output model property?

### ISSUE THREAD

**Issue by enverkrinickii** [zzzprojects/EntityFrameworkExtras#40]
In stored procedure I have property "**e-mail**" in result model -> legacy
in c# class code I have property "**e_mail**".
How to map them?

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

Are you looking to output value such as this example: https://github.com/zzzprojects/EntityFrameworkExtras/blob/master/Z.EntityFrameworkExtras.labEF6/Request_OutputParam.cs

```csharp
[StoredProcedureParameter(SqlDbType.Decimal, Direction = ParameterDirection.Output, Precision = 5, Scale = 4)]
public decimal? ParameterDoubleOutput { get; set; }
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by enverkrinickii** [comment]
Hello @JonathanMagnan 
No, please see which model mu stored procedure returns
![image](https://user-images.githubusercontent.com/25920537/88219229-f60e8300-cc69-11ea-8554-8da0f6742cf3.png)
As you can see there is an **e-mail** property, but in c# code I can't name property like this. So I named it **e_mail**
![image](https://user-images.githubusercontent.com/25920537/88219469-51407580-cc6a-11ea-9184-acb32cf3169d.png)
And when I execute stored procedure I have next exception:
![image](https://user-images.githubusercontent.com/25920537/88219583-7b923300-cc6a-11ea-880c-dbb8ae55e0f0.png)

**Comment by JonathanMagnan** [comment]
Ohh thank you, now I understand the issue correctly :)

**Comment by JonathanMagnan** [comment]
Did you try the `ParameterName` property in the attribute?

```csharp
[StoredProcedureParameter(ParameterName = "e-mail")]
public string e_mail { get; set; }
```

**Comment by enverkrinickii** [comment]
No, because it is output model:
![image](https://user-images.githubusercontent.com/25920537/88255903-592c0400-ccc2-11ea-991b-2a4ed184b001.png)
not input
![image](https://user-images.githubusercontent.com/25920537/88255925-6f39c480-ccc2-11ea-9b7c-ba17f277b3e2.png)

**Comment by JonathanMagnan** [comment]
In this case, we are in Entity Framework, so you need to map your column such as:

```csharp
[Column("e-mail")]
public String e_mail { get; set; }
```

If the `OtherEmployeesInfoData` is not part of your model, I don't think the scenario would be currently supported.

Here is a full example:

```csharp
using EntityFrameworkExtras.EFCore;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data; 
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Z.EntityFrameworkExtras.Lab.EFCore30
{
	class Request_OutputParam
	{ 
		public static void Execute()
		{
			// Create BD 
			using (var context = new EntityContext())
			{
				Z.EntityFrameworkExtras.Lab.EFCore30.My.CreateBD(context);
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}

			// SEED  
			using (var context = new EntityContext())
			{
				for (int i = 0; i < 3; i++)
				{
					context.EntitySimples.Add(new EntitySimple { e_mail = i.ToString() });
				}

				context.SaveChanges();
			} 

			// TEST  
			using (var context = new EntityContext())
			{
				var connection = context.Database.GetDbConnection();
				connection.Open();
				using (var commande = connection.CreateCommand())
				{
					commande.CommandText = @"   
if exists (select 1 from sys.procedures where name = 'PROC_Get_EntitySimple')
BEGIN
DROP PROCEDURE [dbo].[PROC_Get_EntitySimple]
END 
						";
					commande.ExecuteNonQuery();
				} 

				using (var commande = connection.CreateCommand())
				{
					commande.CommandText = @"    
CREATE PROCEDURE [dbo].[PROC_Get_EntitySimple]
 


AS
BEGIN  

Select ID, [e-mail]  from EntitySimples 
END
						";
					commande.ExecuteNonQuery();
				} 

			}

			// TEST  
			using (var context = new EntityContext())
			{
				var proc_Get_EntitySimple = new Proc_Get_EntitySimple() {   }; 
				var entity = context.Database.ExecuteStoredProcedureFirstOrDefault<EntitySimple>(proc_Get_EntitySimple); 
				var list = context.EntitySimples.ToList();
			} 
		}

		public class EntityContext : DbContext
		{
			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseSqlServer(new SqlConnection(Z.EntityFrameworkExtras.Lab.EFCore30.My.ConnectionStringTimeOut));

				base.OnConfiguring(optionsBuilder);
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }
			 
		}

		[StoredProcedure("PROC_Get_EntitySimple")]
		public class Proc_Get_EntitySimple
		{ 
		}
 
 		public class EntitySimple
		{
			public int ID { get; set; } 
			[Column("e-mail")]
			public String e_mail { get; set; }
		}
	}
}
```

**Comment by enverkrinickii** [comment]
Hello @JonathanMagnan 
It works.
Thank you and sorry for disturb

**Comment by enverkrinickii** [comment]
Hello!
I found it works with simple names, see screenshot below:

**Comment by enverkrinickii** [comment]
I found it works with simple names, but not with names with underline, see screenshot below:
![image](https://user-images.githubusercontent.com/25920537/106895559-6e69fc80-6701-11eb-896f-a1e5fcefdf49.png)

**Comment by JonathanMagnan** [comment]
Thank you for reporting, we will look at it

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

My developer tried it and didn't get any issue. Perhaps you were missing something on your side? Otherwise, please provide us a full project example that doesn't work.

Here was one of his test he did:

```csharp
using EntityFrameworkExtras.EFCore;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data; 
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Z.EntityFrameworkExtras.Lab.EFCore30
{
	class Request_OutputParam
	{ 
		public static void Execute()
		{
			// Create BD 
			using (var context = new EntityContext())
			{
				Z.EntityFrameworkExtras.Lab.EFCore30.My.CreateBD(context);
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}

			// SEED  
			using (var context = new EntityContext())
			{
				for (int i = 0; i < 3; i++)
				{
					context.EntitySimples.Add(new EntitySimple { e_mail = i.ToString(), StartDate= DateTime.Now });
				}

				context.SaveChanges();
			} 

			// TEST  
			using (var context = new EntityContext())
			{
				var connection = context.Database.GetDbConnection();
				connection.Open();
				using (var commande = connection.CreateCommand())
				{
					commande.CommandText = @"   
if exists (select 1 from sys.procedures where name = 'PROC_Get_EntitySimple')
BEGIN
DROP PROCEDURE [dbo].[PROC_Get_EntitySimple]
END 
						";
					commande.ExecuteNonQuery();
				} 

				using (var commande = connection.CreateCommand())
				{
					commande.CommandText = @"    
CREATE PROCEDURE [dbo].[PROC_Get_EntitySimple]
 


AS
BEGIN  

Select ID, [e-mail], [Start_Date]  from EntitySimples 
END
						";
					commande.ExecuteNonQuery();
				} 

			}

			// TEST  
			using (var context = new EntityContext())
			{
				var proc_Get_EntitySimple = new Proc_Get_EntitySimple() {   }; 
				var entity = context.Database.ExecuteStoredProcedureFirstOrDefault<EntitySimple>(proc_Get_EntitySimple); 
				var list = context.EntitySimples.ToList();
			} 
		}

		public class EntityContext : DbContext
		{
			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseSqlServer(new SqlConnection(Z.EntityFrameworkExtras.Lab.EFCore30.My.ConnectionStringTimeOut));

				base.OnConfiguring(optionsBuilder);
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }
			 
		}

		[StoredProcedure("PROC_Get_EntitySimple")]
		public class Proc_Get_EntitySimple
		{ 
		}

		[StoredProcedure("PROC_Get_intNullable")]
		public class Proc_PROC_Get_intNullable
		{
		}

		public class EntitySimple
		{
			public int ID { get; set; } 
			[Column("e-mail")]
			public String e_mail { get; set; }
			[Column("Start_Date")]
			public DateTime StartDate { get; set; }
		}
	}
}
```

**Comment by enverkrinickii** [comment]
Hello @JonathanMagnan 
I use this library in another way
Input model
`[StoredProcedure("SP_Test")]
    public class LoadEmployeeData
    {
        [StoredProcedureParameter(SqlDbType.DateTime, ParameterName = "OnDate")]
        public DateTime? OnDate { get; set; }
        [StoredProcedureParameter(SqlDbType.Int, ParameterName = "ResourceID")]
        public int ResourceId { get; set; }
    }
}`
Output model
`using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace WebTime.DAL.Models.Financial.EmployeeCosts
{
    public class LoadEmployeeDataModel
    {
        public int RowType { get; set; }

        [Column("ID")]
        public int Id { get; set; }
        [Column("Start_Date")]
        public DateTime StartDate { get; set; }
        [Column("Resource_ID")]
        public int ResourceId { get; set; }
       
        public string Creator { get; set; }
        public string Created { get; set; }
        public string Modifier { get; set; }
        [Column("Last_Modified")]
        public string LastModified { get; set; }
    }
}
`
Context class: 
`public virtual Task<IEnumerable<LoadEmployeeDataModel>> SP_Test(
            LoadEmployeeDatamodel)
        {
            return this.Database.ExecuteStoredProcedureAsync<LoadEmployeeCostResultDataModel>(model);
        }`
Call:
`namespace temp
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var data = new List<LoadEmployeeDataModel>();
            using (var context = new WebtimeDataContext())
            {
                data = (await context.P_SEC_LoadEmployeeCost(new LoadEmployeeCostInputModel()
                {
                    ResourceId = 333333,
                    OnDate = null
                })).ToList();
            }

            Console.ReadKey();
        }
    }

}`
