### ISSUE TITLE
How to map output model property? 

### ISSUE THREAD

**Issue by enverkrinickii** [zzzprojects/EntityFrameworkExtras#43]
Hello @JonathanMagnan 
I use this library in another way

```csharp
[StoredProcedure("SP_Test")]
public class LoadEmployeeData
{
    [StoredProcedureParameter(SqlDbType.DateTime, ParameterName = "OnDate")]
    public DateTime? OnDate { get; set; }
    [StoredProcedureParameter(SqlDbType.Int, ParameterName = "ResourceID")]
    public int ResourceId { get; set; }
}


//Output model
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace WebTime.DAL
{
    public class LoadEmployeeDataModel
    {
        public int RowType { get; set; }
        [Column("ID")]
        public int Id { get; set; }
        [Column("Start_Date")]
        public DateTime StartDate { get; set; }
        [Column("Resource_ID")]
        public int ResourceId { get; set; }
        public string Creator { get; set; }
        public string Created { get; set; }
        public string Modifier { get; set; }
        [Column("Last_Modified")]
        public string LastModified { get; set; }
    }
}
//Context class: 
public virtual Task<IEnumerable<LoadEmployeeDataModel>> SP_Test(
            LoadEmployeeData model)
{
    return this.Database.ExecuteStoredProcedureAsync<LoadEmployeeDataModel>(model);
}
//Call:
namespace temp
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var data = new List<LoadEmployeeDataModel>();
            using (var context = new WebtimeDataContext())
            {
                data = (await context.SP_Test(new LoadEmployeeData()
                {
                    ResourceId = 333333,
                    OnDate = null
                })).ToList();
            }
            Console.ReadKey();
        }
    }
}
```

_Originally posted by @enverkrinickii in https://github.com/zzzprojects/EntityFrameworkExtras/issues/40#issuecomment-783326948_

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

My developer will look at it

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

My developer is asking for a runnable project or example.

There is some essential element that's missing in your example such as the `Context`, the `P_SEC_LoadEmployeeCost`

We want to be sure if he passes time on this issue that he has all elements to investigate it.

Make sure to provide a full runnable example or better, a project if you want we investigate it.

**Comment by enverkrinickii** [comment]
Hello @JonathanMagnan , I have updated my comment

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

As asked, we would like to have a runnable project or example.

You currently show only some part of it.

If you need, take example of what my developer provided you: https://github.com/zzzprojects/EntityFrameworkExtras/issues/40#issuecomment-775657411

Everything is included, even the stored procedure creation

**Comment by enverkrinickii** [comment]
Hello @JonathanMagnan
Unfortunately i can't share it with you because of organization policy
I provided you a code sample how I use your library and as you can see, I return function result instead of data set

**Comment by JonathanMagnan** [comment]
We didn't ask for your company project, we asked for a runnable project or example.

It can contain exactly what you provided but just make sure it compile, run and show the issue.

**Comment by enverkrinickii** [comment]
Not sure that it possible because of I'm using DB first aproach an scaffold it

**Comment by enverkrinickii** [comment]
Have you developer tried to return ``var entity = context.Database.ExecuteStoredProcedure<EntitySimple>(proc_Get_EntitySimple); `` instead of ``var list = context.EntitySimples.ToList();``

**Comment by JonathanMagnan** [comment]
Hello @enverkrinickii ,

Unfortunately, we cannot investigate further this request.

We requested several times a project, however, it was not provided. 

Don't hesitate to provide a project so that we can assist you better. 

Best regards,

Jon
