### ISSUE TITLE
Is there a way to automatically map a query result set to a nested object structure?

### ISSUE THREAD

**Issue by stamminator** [zzzprojects/EntityFrameworkExtras#44]
## 1. Description
Is there a way to automatically map a query result set to a nested object structure without having to first materialize to a flat type, then manually map the results to the nested structure? I know that LINQ-to-Entities supports this via mapped entities and navigation properties, but I'm just looking for a couple of eggs rather than the whole farm.

## 3. Fiddle or Project
Given a query result set that looks like this:

![image](https://user-images.githubusercontent.com/10633170/140074505-95963fa0-3008-489c-9186-3cc3dbe9c143.png)

I'd like to materialize my results somewhat like this:
```c#
public class SalesReportRecord
{
    public int BranchId { get; set; }
    public FinancialTotals YTD { get; set; }
    public FinancialTotals T12 { get; set; }
}

public class FinancialTotals
{
    public decimal Price { get; set; }
    public int Count { get; set; }
}

public static List<SalesReportRecord> GetSalesReport()
{
    using (DbContext context = GetContext())
    {
        List<SalesReportRecord> results = 
            context.Database.SqlQuery<SalesReportRecord>("EXEC dbo.SalesReport").ToList();
        return results;
    }
}
```

## 4. Any further technical details
If there is no way, I think this would make a great addition to EFExtras. It would probably have to use some sort of convention to know how to map the column names to the properties and subproperties.

**Comment by stamminator** [comment]
Thanks @JonathanMagnan. In the example on the page you linked, I assume that works with a single result set that looks like this?

![image](https://user-images.githubusercontent.com/10633170/140083237-ada89286-caee-4dff-9555-de5a9b04bc9f.png)

If so, is there any support for something like this? It would have to have some of column name prefixing convention or configuration via the `ComplexType` attibute I assume.

```c#
public class Author
{
    public int AuthorId { get; set; }
    public string Name { get; set; }
    public Address BillingAddress { get; set; }
    public Address ShippingAddress { get; set; }
}
```

**Comment by JonathanMagnan** [comment]
Unfortunately, after some research, it looks like that complex type is not supported with `SqlQuery`: https://github.com/dotnet/ef6/issues/107

This would be sure a new good feature but unfortunately, time is missing on our side so this is just simply impossible at this moment.

However, we added your suggestion in our wishlist.

Best Regards,

Jon

**Comment by stamminator** [comment]
Understood, thanks for looking into it Jon.
